### ISSUE TITLE
How to get the imputed value for each cell of each gene- scvi version 0.9.1

### ISSUE THREAD

**Issue by yanwengong** [YosefLab/scvi-tools#1022]
I hope to get the imputed matrix of gene x cells. Is there a function to get such values?
I didn't find similar API like posterior.imputation(), which is probably related with older version of scVI.

**Comment by adamgayoso** [comment]
You may use this [function](https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCVI.get_normalized_expression.html#scvi.model.SCVI.get_normalized_expression).

Also, in the future, it will be helpful if you post these sorts of issues on our discourse [forum](https://discourse.scvi-tools.org/).
