### ISSUE TITLE
Import error (for querying) with scvi 0.9.0

### ISSUE THREAD

**Issue by davemcg** [YosefLab/scvi-tools#1026]
Created a model with scVI 0.9.0

I'm unable to load the model with `scvi.model.SCVI.load_query_data`

I am getting an error about an 'unexpected keyword model_kwargs'

```
INFO     Using data from adata.X                                                             
INFO     Computing library size prior per batch                                              
WARNING  This dataset has some empty cells, this might fail inference.Data should be filtered
         with `scanpy.pp.filter_cells()`                                                     
/usr/local/lib/python3.7/dist-packages/scvi/data/_anndata.py:711: UserWarning: Category 11 in adata.obs['_scvi_batch'] has fewer than 3 cells. SCVI may not train properly.
  'Making .obs["{}"] categorical failed. Expected categories: {}. '
INFO     Registered keys:['X', 'batch_indices', 'local_l_mean', 'local_l_var', 'labels']     
INFO     Successfully registered anndata object containing 22740 cells, 5000 vars, 80        
         batches, 1 labels, and 0 proteins. Also registered 0 extra categorical covariates   
         and 0 extra continuous covariates.                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-27ef28f3d82c> in <module>()
      1 vae_query = scvi.model.SCVI.load_query_data(  
      2     adata_query_HVG,
----> 3     scVI_model_dir_path
      4 )

2 frames
/usr/local/lib/python3.7/dist-packages/scvi/model/scvi.py in __init__(self, adata, n_hidden, n_latent, n_layers, dropout_rate, dispersion, gene_likelihood, latent_distribution, use_cuda, **model_kwargs)

TypeError: __init__() got an unexpected keyword argument 'model_kwargs'
```

You can reproduce the issue with this Google Colab (this was functioning earlier with a scVI 0.8.0 model but I was trying to update to 0.9.0)

https://colab.research.google.com/gist/davemcg/b86de9ca480f8e8812650eb66ba9a417/query-sceiad-with-scvi.ipynb

```pytb
[ERROR HERE]
```

#### Versions:

> 0.9.0

**Comment by davemcg** [comment]
And yes, this isn't fully reproducible as I'm not doing the upstream scVI model creation.. In fact there's a 80% chance I've just mis-understood something in the 0.8 -> 0.9 transition.

**Comment by davemcg** [comment]
This is a weird error because it suggests some kind of mismatch of the version? It *should* have been made with 0.9.0....but is there a way to confirm that from one of the files in the scVI model directory?

**Comment by adamgayoso** [comment]
To make sure we understand, what version was the reference model trained on?

**Comment by adamgayoso** [comment]
Also, I just ran the notebook and had no such error, though you will need to change the line

```
vae_query.train(n_epochs = 50,  n_epochs_kl_warmup=50, weight_decay=0.0)
```

Based on the latest version of our tutorial.

**Comment by galenxing** [comment]
Hey,

I just ran the notebook and it ran fine for me. I made one edit to the `vae_query.train()` call which you can see here: https://colab.research.google.com/gist/galenxing/b225f0100aa6a5b6b91f148b239047a5/query-sceiad-with-scvi.ipynb

Let me know if you still have issues!

**Comment by galenxing** [comment]
Woops, didn't see Adam's comments. But yea that edit is in my notebook.

**Comment by davemcg** [comment]
Oh FFS I'm guessing there was some colab cache thing or something. I'll check it myself in a bit.

**Comment by davemcg** [comment]
Yeah...stupid notebook stupid works now. I was updating to 0.9.0 and I missed a line so originally I had the 0.8.0 model downloaded....I'm guessing the wget command wasn't actually overwriting the file when I re-downloaded and instead was appending incrementing digits....which would mean that scVI 0.9.0 was trying to load a 0.8.0 model.

**Comment by davemcg** [comment]
Thanks for your help!
