### ISSUE TITLE
Error importing gimVI

### ISSUE THREAD

**Issue by jhkliu42** [YosefLab/scvi-tools#1029]
I'm trying to use gimVI based on the tutorial (https://docs.scvi-tools.org/en/stable/user_guide/notebooks/gimvi_tutorial.html) and am having trouble importing it.

I've installed the most recent of scVI-tools using "pip install scvi-tools", and can run "import scvi" fine. However, if I try running "from scvi.external import GIMVI" I get an error.

I know this is probably a simple fix but I'm a bit new to Python and managing different packages so just wanted to make sure that I approach this in the most principled way - thanks.

```python
from scvi.external import GIMVI
```

```pytb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-555-57502f702848> in <module>
     14 import math
     15 import scvi
---> 16 from scvi.external import GIMVI

ModuleNotFoundError: No module named 'scvi.external'

```

#### Versions:

> VERSION '0.8.1'

**Comment by adamgayoso** [comment]
Hi, I believe this will be fixed if you install the latest version of scvi-tools, which is version 0.9.1. You can do that with

```python
pip install scvi-tools==0.9.1
```

**Comment by adamgayoso** [comment]
Please let us know if you have further issues.

**Comment by jhkliu42** [comment]
Hello,
I installe the 0.9.1 version and it seemed to go well. There seems to be a dependency issue with PyTorch now, though, and I get the following error message when importing GIMVI. I've tried installing the latest version of PyTorch but that didn't fix the issue.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-564-57502f702848> in <module>
     14 import math
     15 import scvi
---> 16 from scvi.external import GIMVI

~/miniconda3/lib/python3.8/site-packages/scvi/external/__init__.py in <module>
----> 1 from .cellassign import CellAssign
      2 from .gimvi import GIMVI
      3 from .solo import SOLO
      4 from .stereoscope import RNAStereoscope, SpatialStereoscope
      5 

~/miniconda3/lib/python3.8/site-packages/scvi/external/cellassign/__init__.py in <module>
----> 1 from ._model import CellAssign
      2 from ._module import CellAssignModule
      3 
      4 __all__ = ["CellAssign", "CellAssignModule"]

~/miniconda3/lib/python3.8/site-packages/scvi/external/cellassign/_model.py in <module>
      6 import torch
      7 from anndata import AnnData
----> 8 from pytorch_lightning.callbacks import Callback
      9 from pytorch_lightning.callbacks.early_stopping import EarlyStopping
     10 

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/__init__.py in <module>
     26 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     27 
---> 28 from pytorch_lightning import metrics  # noqa: E402
     29 from pytorch_lightning.callbacks import Callback  # noqa: E402
     30 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification import (  # noqa: F401
     15     Accuracy,
     16     AUC,

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.classification.auc import AUC  # noqa: F401
     16 from pytorch_lightning.metrics.classification.auroc import AUROC  # noqa: F401

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
     19 from pytorch_lightning.metrics.metric import Metric
     20 

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/functional/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.functional.auc import auc  # noqa: F401
     16 from pytorch_lightning.metrics.functional.auroc import auroc  # noqa: F401

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/functional/accuracy.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
     19 
     20 

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/helpers.py in <module>
     17 import torch
     18 
---> 19 from pytorch_lightning.metrics.utils import select_topk, to_onehot
     20 from pytorch_lightning.utilities import LightningEnum
     21 

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.utilities import rank_zero_warn
     19 
     20 METRIC_EPS = 1e-6

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     15 
     16 import numpy
---> 17 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     18 from pytorch_lightning.utilities.distributed import (  # noqa: F401
     19     AllGatherGrad,

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     23 
     24 from pytorch_lightning.utilities.exceptions import MisconfigurationException
---> 25 from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
     26 
     27 if _TORCHTEXT_AVAILABLE:

~/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py in <module>
     77 _HYDRA_AVAILABLE = _module_available("hydra")
     78 _HYDRA_EXPERIMENTAL_AVAILABLE = _module_available("hydra.experimental")
---> 79 _NATIVE_AMP_AVAILABLE = _module_available("torch.cuda.amp") and hasattr(torch.cuda.amp, "autocast")
     80 _OMEGACONF_AVAILABLE = _module_available("omegaconf")
     81 _RPC_AVAILABLE = not _IS_WINDOWS and _module_available('torch.distributed.rpc')

AttributeError: module 'torch.cuda' has no attribute 'amp'

**Comment by adamgayoso** [comment]
It should've updated automatically but I think you need to upgrade Pytorch lightning

https://www.pytorchlightning.ai/
