### ISSUE TITLE
RE: conversion of Seurat object with ADT assay to anndata

### ISSUE THREAD

**Issue by Nusob888** [YosefLab/scvi-tools#1062]
Thank you for the fantastic tool. 

I am attempting to process a pre-processed Seurat object to the anndata format required for TotalVI. The trouble I am having, is that the R and Seurat vignette does not give an example where one converts the ADT data into a format that is compatible with SCVI.

In particular it is not clear in the documentation how the "protein_expression_obsm_key" is generated. Is it possible to manually add a concatenated matrix of RNA and protein from a Seurat object and manually assign a "protein_expression_obsm_key"? If so, can that vignette be added? or the procedure explained here?

Many thanks in advance

**Comment by adamgayoso** [comment]
So I believe you need to make another anndata object just for the protein data using the same method for the RNA data, but using the correct protein Seurat "assay". Then you can do `rna_adata.obs["protein_expression"] = protein_adata.to_df()` in Python.

You might also be able to save the seurat object as h5ad and read directly in Python as in this [tutorial](https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html) for scVelo.

Also we do appreciate these sorts of questions to be raised at our [Discourse forum](https://discourse.scvi-tools.org/).

**Comment by Nusob888** [comment]
Thank you forsaking the time to respond, much appreciated. 

Apologies, I hadn't realised there was a Discourse forum; am not an avid user of it, but will transfer usage questions to there.
