### ISSUE TITLE
using highly_variable_intersection instead of subset

### ISSUE THREAD

**Issue by dm8000** [YosefLab/scvi-tools#1075]
Hello

In [this tutorial](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/harmonization.html) I see that the highly variable genes are subset before the integration. Because I need to subset a cell type and cluster them again, I am unable to select new highly variable genes (attempting to use adata.raw has many inconveniences it seems). I see `scvi.data.setup_anndata` has no option to use the highly_variable_intersection key in adata.var. Is there any workaround?

**Comment by adamgayoso** [comment]
you will have to make copies of the anndata objects and use them separately it sounds like, though I do not entirely understand what you'd like to do. Also in the future, we do appreciate these sorts of questions on our [discussion forum](https://discourse.scvi-tools.org/).
