### ISSUE TITLE
Loading saved DestVI.from_rna_model dosn't consider two anndatas used to create model

### ISSUE THREAD

**Issue by BradBalderson** [YosefLab/scvi-tools#1087]
When saving the DestVI model, it requires the anndata as input to scvi.model.SCVI.load. 
There are two anndatas used to create the model; the reference scRNA-seq data, or the spatial transcriptomics data. Trying either of these, I get errors when attempting to reload the model. 

It appears reloading the data uses some information from both anndata,
but the scvi.model.SCVI.load function was only built to consider one. 

I am following the vignette: https://docs.scvi-tools.org/en/stable/user_guide/notebooks/DestVI_tutorial.html
So the creation of the model is shown as below:
```
scvi.data.setup_anndata(vdata_, labels_key='cell_labels')
sc_model = CondSCVI(vdata_, weight_obs=True)
sc_model.train(max_epochs=100)

###### Now performing the deconvolution #########
scvi.data.setup_anndata(data_, batch_key='batch')

st_model = DestVI.from_rna_model(data_, sc_model)

st_model.train(max_epochs=250)

# The proportions ! #
data_.obsm["proportions"] = st_model.get_proportions()
```

Then I attempt to save using either the scRNA-seq adata (vdata_) or the spatial transcriptomics adata (data_):
In the first case:
```
st_model.save(f"{h5_dir}my_model/")
model = scvi.model.SCVI.load(f"{h5_dir}my_model/", vdata_)
```

In the second case, I run:

```
model = scvi.model.SCVI.load(f"{h5_dir}my_model/", data_)
```

In the first case (scRNA-seq as the adata), i get this error:
```pytb
scvi/data/_anndata.py in _transfer_batch_and_labels(adata_target, categorical_mappings, extend_categories)
    510             raise KeyError(
    511                 '.obs["{}"] was used to setup source, but not found in target.'.format(
--> 512                     original_key
    513                 )
    514             )

KeyError: '.obs["batch"] was used to setup source, but not found in target.'
```

In the second case (spatial as adata), i get this error:
```pytb
scvi/model/_scvi.py in __init__(self, adata, n_hidden, n_latent, n_layers, dropout_rate, dispersion, gene_likelihood, latent_distribution, **model_kwargs)
    102             gene_likelihood=gene_likelihood,
    103             latent_distribution=latent_distribution,
--> 104             **model_kwargs,
    105         )
    106         self._model_summary_string = (

TypeError: __init__() got an unexpected keyword argument 'cell_type_mapping'
```

#### Versions:
scvi.__version__
'0.11.0'
> VERSION

Thanks alot for developing a fantastic tool!

**Comment by adamgayoso** [comment]
Thanks for raising this. The issue is actually the docstring is shared by all of our models so the examples are incorrect. You should use the `load` class method of the class you used to train the model (e.g., `DestVI.load`)

**Comment by BradBalderson** [comment]
That's great, thankyou very much!

**Comment by adamgayoso** [comment]
Reopening this so we don't forget to address this confusion in the docs.
