### ISSUE TITLE
new version doesn't work with Seurat tutorial in User Docs

### ISSUE THREAD

**Issue by Varix** [YosefLab/scvi-tools#1089]
While attempting an integration with scvi I followed the user guide on the website to install and setup. Install with `reticulate` as per the user guide worked without error following these command:

```
library(reticulate)
py_install("scanpy")
py_install("scvi")

sc <- import('scanpy', convert = FALSE)
scvi <- import('scvi', convert = FALSE)
```
however, running any of the scvi commands / setting settings or passing data resulted in the following error (note: the sc function to convert to AnnData worked fine): `AttributeError: module 'scvi' has no attribute 'data'`

a quick google search found an issue someone had very similar in python and the solution was that data structure had changed of the package and they needed to install the newest version. I am not sure if this error I am seeing is because I need a NEW version of scVI OR if the user docs is for the old one.

I will keep troubleshooting and try to figure out which one, this is a clean new install of scVI so there shouldnt be any old code hiding anywhere that I know of , but conda repo could be pulling old package..  but if someone already knows the answer and wants to give me an idea of where to look, i would be very grateful.

```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'scvi' has no attribute 'data'
```

```R
scvi$settings$progress_bar_style = 'tqdm'

scvi$data$setup_anndata(adata)

```

```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'scvi' has no attribute 'data'
```

#### Versions:

> VERSION
scvi-0.1.6 ?? according to bioconda
Python 3.8.5

**Comment by adamgayoso** [comment]
How did you install scvi via conda?

Note that the name is scvi-tools for installation. See the following link:

https://anaconda.org/bioconda/scvi-tools
https://docs.scvi-tools.org/en/stable/installation.html

**Comment by Varix** [comment]
thank you for the links, I used `py_install("scvi")` inside R , following this --> https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scvi_in_R.html 

will check out your links and try scvi-tools , if this is just cause I installed a different package with a similar name  , I am going to face palm so hard

**Comment by Varix** [comment]
hmmm I seem to be in a loop, switching conda environments doesnt seem to impact available libraries and conda_remove() isnt uninstalling anything to try and load a different version. I will keep playing with it and hopefully make some progress and will update the thread if I figure anything out.

**Comment by adamgayoso** [comment]
> Thank you for the links, I used `py_install("scvi")` inside R , following this --> https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scvi_in_R.html

Our package used to be called `scvi`, but now it's called `scvi-tools`. Even with the name change it's still `import scvi`, so here you should `py_install("scvi-tools")`

**Comment by Varix** [comment]
Okay can confirm this approach removed my initial issues.  Reticulate did not like (or was pulling from) the wrong sources for scvi-tools for its native conda installation of libraries... using conda directly outside of reticulate solved the problem as you suggested.

I am having a new issue with pyTorch not seeing my 2080 Ti GPU that I would love to throw cores for training on, but that is a separate config issue not related to scVI.  I am closing the issue and thank you for taking the time to help me out.

I might write a step by step blog post on how to configure this for first timers moving forward with R.  At First I was thinking of doing a fork and PR to update the documentation but honestly, the documentation is fine in terms of what to do, its just separated up in a way that until you told me the order I didn't get by default from the traditional reticulate approach... so changing documentation is probably overkill for a small user base of R users with reticulate experience and previous zero scVI use...

**Comment by adamgayoso** [comment]
Probably some cuda driver issue with your gpu. 

If you write a blog post we can link to it from our installation page. Feel free to make a PR when/if you do it.
