### ISSUE TITLE
Get differential expression analysis for all genes after feature selection (highly variable genes)

### ISSUE THREAD

**Issue by KANG-BIOINFO** [YosefLab/scvi-tools#1094]
Hi,

Thanks so much for the fantastic tool you developed. In my analysis, I used highly variable genes to do feature selection and run the model, and later use _model.differential_expression_ to do DE analysis. However, the output of DE analysis is only limited to the number of highly variable genes. Is there any way that users can get DE output for all genes while still using highly variable genes for feature reduction downstream analysis?

Thanks!

**Comment by adamgayoso** [comment]
The DE is based on the fit of the model. As the model only sees the genes that are provided to it, it is therefore not possible to do DE on other genes. 

Thank you for using scvi-tools. We do appreciate these sorts of questions at our discourse site: https://discourse.scvi-tools.org/

**Comment by KANG-BIOINFO** [comment]
Thanks so much for your explanation! Really appreciate it!
