### ISSUE TITLE
Questions about the dataset you used in scVI demo

### ISSUE THREAD

**Issue by ChineseBest** [YosefLab/scvi-tools#1105]
Hi, I wonder the NCIB address or number for the dataset in this tutorial:
https://docs.scvi-tools.org/en/stable/user_guide/notebooks/cite_scrna_integration_w_totalVI.html

About the PBMC data you used in this part, do you have any cell type label information here? Thanks a lot.

Sincerely

**Comment by adamgayoso** [comment]
The dataset is described here:

https://www.nature.com/articles/s41592-020-01050-x

It's a concatenation of two publicly available datasets from 10x genomics, and there is no label information.
