### ISSUE TITLE
Usage of HVG in scVI

### ISSUE THREAD

**Issue by ling-lyang** [YosefLab/scvi-tools#1120]
Please raise usage questions at [discourse.scvi-tools.org](https://discourse.scvi-tools.org/)
(I have noticed exactly the same question was raised in #850 but no clear answer was given and it shows closed.)

The question is, does scVI use highly variable genes selected by scanpy?

I ran scvi 1) with no highly variable genes selected, 2) with highly variable genes selected, 3) with highly variable genes selected but manually removed some genes from HVG. 

The results are different for 1) and 2) but the same for 2) and 3). 

This is confusing. Anyone has any idea?

Thanks!
Ling

**Comment by adamgayoso** [comment]
Hi Ling, we do appreciate these types of questions on our discourse site. I've moved it there and will close this issue now.

https://discourse.scvi-tools.org/t/usage-of-hvg-in-scvi/167
