### ISSUE TITLE
[AnnData setup refactor] Make setup_anndata a static class method on the model

### ISSUE THREAD

**Issue by watiss** [YosefLab/scvi-tools#1135]
See [this](https://docs.google.com/document/d/18howmTv4eg6dOBIEaJTpUr1DsS2GaaYmZewgy6lB_ME/edit?usp=sharing) doc for details

Note: We originally considered calling the static setup_anndata method from respective model constructors. However we later decided not to do so due to at least the two issues below:
1. This would be a breaking change as it would break users' flow: today users set up anndata then create the model per our user guides, but with this change the new setup_anndata call with default parameters would clear out their original setup.
2. Ceratin models have factory methods to create them from other models (see SCANVI for example). In these cases we need to provide a way to not set up the anndata again as we intent to use the anndata that was already set up in the original model.

**Comment by adamgayoso** [comment]
Whoops, copied from the wrong issue:

Model specific params (relative to global setup anndata)

All except protein params:

    scANVI
    scVI

All except labels:

    totalVI

All except labels and protein params:

    peakVI
    multivi
    CellAssign

Only layer and labels:

    CondSCVI
    destvi
    RNAStereoscope

Others:

    LinearSCVI (layer and batch key)
    Autozi (layer, batch, labels)
    spatialstereoscope (layer, but uses alternate constructor)
    SOLO (complicated because it uses alternate constructor)
