### ISSUE TITLE
poerty.lock seems incorrect

### ISSUE THREAD

**Issue by watiss** [YosefLab/scvi-tools#1141]
It looks like the checked in poetry.lock file is incorrect. Poetry fails with SolverProblemError because the declared numba and llvmlite versions don’t match. In fact the PyPI numba 0.51.2 release page confirms that it is only compatible with llvmlite 0.34.*.

To reproduce run poetry install on a brand new virtual environment (I used pyenv).

```
poetry install --extras "dev docs tutorials"
```

**Comment by adamgayoso** [comment]
One issue I have with poetry is installation of GPU compatible pytorch. I always have to then install myself and I'm not sure there's a universal version that can go in the lock...

**Comment by watiss** [comment]
@adamgayoso Do you want to open a different issue for that one? I can take a look into it, not sure off top of my head how to do it either.
