### ISSUE TITLE
Some questions about totalVI protein model

### ISSUE THREAD

**Issue by ChineseBest** [YosefLab/scvi-tools#1162]
I wonder why for totalvi, the protein can be modeled into background and foreground, two kinds of components and distribution. Are there any articles I can refer? Thanks.

**Comment by adamgayoso** [comment]
The full description is in the publication here:

https://www.nature.com/articles/s41592-020-01050-x

**Comment by adamgayoso** [comment]
Please feel free to use our forum: https://discourse.scvi-tools.org/

for further discussion
