### ISSUE TITLE
Get_normalized_expression for specific genes

### ISSUE THREAD

**Issue by andrewjkwok** [YosefLab/scvi-tools#1164]
Hi,

When using the `get_normalized_expression` function, I've been trying to reduce the memory usage by specifying only specific genes with the `gene_list` argument (https://discourse.scvi-tools.org/t/get-normalized-expression-function-arguments/140). However, I receive an error:

`ValueError: Value passed for key 'denoised_rna' is of incorrect shape. Values of layers must match dimensions (0, 1) of parent. Value had shape (92009, 3) while it should have had (92009, 4000).`

Is there any idea how this could be fixed? Thanks in advance.

**Comment by adamgayoso** [comment]
Ok actually I misinterpreted this. Is your gene list of length 3? If so, the RNA data cannot be stored back inside the anndata in a layer, you'd have to use obsm
