### ISSUE TITLE
Update tutorials after changes to setup_anndata and library mean/var calculations

### ISSUE THREAD

**Issue by watiss** [YosefLab/scvi-tools#1179]
As a result of [this](https://github.com/YosefLab/scvi-tools/pull/1150) pr and [this](https://github.com/YosefLab/scvi-tools/pull/1123) pr, we should update our tutorials.

- [x] Intro to scvi-tools -> Valeh
- [x] Data loading and prep -> Valeh (modify text as well)
- [x] Interoperability with R (Justin) (move current one in with scrna seq tutorials)
- [x] CITE-seq analysis w totalVI -> Valeh
- [x] Atlas level integration (Adam)
- [x] scANVI -> Valeh
- [x] linearly decoded VAE (Adam)
- [x] CITE-seq and scRNA-seq integration (Adam)
- [x] scArches (Adam)
- [x] gimVI (Justin)
- [x] autoZI (Justin)
- [x] cellassign (Valeh)
- [x] DestVI (Justin)
- [x] peakVI (Justin)
- [x] MultiVI (Mariano)
- [x] Stereoscope (Justin)

**Comment by adamgayoso** [comment]
@jjhong922 let's drop DE on C elegans, the figures don't render correctly on the docs as it is

**Comment by watiss** [comment]
Linked pull requests from the scvi-tutorials repo:
- https://github.com/YosefLab/scvi-tutorials/pull/32
- https://github.com/YosefLab/scvi-tutorials/pull/29
