### ISSUE TITLE
Create release notes

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scvi-tools#1188]
Here's a good example of our format:

https://github.com/YosefLab/scvi-tools/blob/master/docs/release_notes/v0.11.0.rst

**Comment by adamgayoso** [comment]
Perhaps an opportunity to set this up too:

https://pypi.org/project/towncrier/

**Comment by watiss** [comment]
> Perhaps an opportunity to set this up too:
> 
> https://pypi.org/project/towncrier/

Creating a separate issue for this since we are not handling it as part of this change
