### ISSUE TITLE
scVI Reference Model Zoo

### ISSUE THREAD

**Issue by jjhong922** [YosefLab/scvi-tools#1194]
To lower the barrier for usage of scVI models, we would like to provide pretrained models for Tabula Sapiens datasets. While long term we may want to rely on a third party managed data/model zoo like [sfaira](https://github.com/theislab/sfaira), we would also like a short term option for this purpose.

The proposal is as follows:
- Users will access pretrained models via a `TabulaSapiensReference` object from which users can both list available reference models with `get_available_reference_models` and load a model via `load_reference_model(self, model_id: str, adata: Optional[AnnData] = None, load_reference_adata: bool = False)`, where either if `adata` is passed in, we load it via the scArches mixin, and we optionally load the reference adata. If `load_reference_adata` is `False` and `adata` is `None` then a ValueError would be thrown.
- The `TabulaSapiensReference` object would be backed by a `ZenodoReferenceStore` object which would serve as the lower level interface with the Zenodo repos where we would store the model and adata objects.
- In order to provide a parsable metadata for each entry in the `ZenodoReferenceStore`, we will use a util to convert between a NamedTuple object containing all metadata relevant to a pretrained model to a string, which can later be parsed back into the NamedTuple object.

**Comment by adamgayoso** [comment]
Closing this as we have another repo for this
