### ISSUE TITLE
Cannot install scvi-tools with conda

### ISSUE THREAD

**Issue by FPetitprez** [YosefLab/scvi-tools#1322]
Hello, I am trying to install scvi tools with conda. I followed the instruction found [here](https://docs.scvi-tools.org/en/stable/installation.html). I created and activated a conda environment, but when I try to install scvi-tools in it, it fails to solve the environment twice (frozen and flexible solve) with current_repodata.json, then with "next repodata", the solving environment step keeps on turning for hours and nothing happens. I have the following text on my console:

`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /`

And it just keeps on turning. Thank you in advance for your help!

```bash
conda activate scvi-env
conda install scvi-tools -c bioconda -c conda-forge
```

#### Versions:
Ubuntu 20.04
Conda 4.11.0

**Comment by brianpenghe** [comment]
Same error!

**Comment by adamgayoso** [comment]
Thank you, we will look into this

**Comment by adamgayoso** [comment]
by chance are you using python 3.6? we do not support python 3.6 anymore (and a lot of packages are removing support)

**Comment by FPetitprez** [comment]
Hi, I tried with python 3.7 and 3.8

**Comment by adamgayoso** [comment]
Looks like an issue with other bioconda packages too (try without `-c conda-forge`). I'm trying to move us to conda-forge, so hopefully that fixes it

**Comment by FPetitprez** [comment]
Without the `-c conda-forge`, it finishes with an error:

`Found conflicts! Looking for incompatible packages.

This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
`

**Comment by adamgayoso** [comment]
Ok we are on conda-forge now, installation works with

```
conda install scvi-tools -c conda-forge
```

**Comment by brianpenghe** [comment]
> conda install scvi-tools -c conda-forge

It still doesn't work. Are you sure you still support python 3.7?

**Comment by adamgayoso** [comment]
> It still doesn't work. Are you sure you still support python 3.7?

Yes, tested to work on ubuntu with `conda install scvi-tools -c conda-forge`, please don't include bioconda channel.

What OS are you using? If using a mac m1, the installation does not currently work with conda

**Comment by brianpenghe** [comment]
OK now the error messages changed. Do you know why this happened?
I'm using linux on google cloud. Any ideas of the 404 Client Error?
![image](https://user-images.githubusercontent.com/4110443/157647092-0c325843-59d7-42ed-878c-2254254f6660.png)

**Comment by adamgayoso** [comment]
Not sure, maybe `conda update conda` in your base env and try with a new env?

**Comment by brianpenghe** [comment]
> Not sure, maybe `conda update conda` in your base env and try with a new env?

This is the error I get when updating conda
![image](https://user-images.githubusercontent.com/4110443/164086002-cfd21ed9-077e-48db-8d14-e33ac2b0b036.png)

Do you know why that happens?

**Comment by brianpenghe** [comment]
Actually I managed to conda install scvi by using python 3.8 instead of python 3.7. Hope this is helpful to everyone.

**Comment by adamgayoso** [comment]
you need to first exit the environment you're in I believe, `conda deactivate` then it should work

**Comment by brianpenghe** [comment]
> you need to first exit the environment you're in I believe, `conda deactivate` then it should work

Thanks. Does this look normal?

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: / Config option `kernel_spec_manager_class` not recognized by `UninstallNBExtensionApp`.
Uninstalling jupyter-js-widgets jupyter-js-widgets/extension
Removing: /opt/conda/share/jupyter/nbextensions/jupyter-js-widgets
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/use-collaborative

\ Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/use-collaborative

done
```
