### ISSUE TITLE
Fork module does not work as expected 

### ISSUE THREAD

**Issue by flde** [YosefLab/scvi-tools#1358]
Hi, I forked the repository following the [instructions](https://docs.scvi-tools.org/en/stable/contributing/index.html). When I run the following everything works and I can use the latent space for clustering etc. 

adata = scvi.data.pbmc_dataset()
sc.pp.highly_variable_genes(adata, flavor='seurat_v3', n_top_genes=2000, batch_key='batch', subset=True)  
scvi.model.SCVI.setup_anndata(adata, copy=True, batch_key='batch')  
model = scvi.model.SCVI(adata, gene_likelihood='nb')  
model.train()  
model.save('model/', overwrite=True, save_anndata=True)  
adata.write('adata.h5ad')

However when I run SOLO 

solo_batch_1 = scvi.external.SOLO.from_scvi_model(model, restrict_to_batch=0)
solo_batch_1.train()

it fails with the following error 
RuntimeError: Early stopping conditioned on metric `validation_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`, `train_loss_step`, `train_loss_epoch`

I then checked the model directory from scvi and there is only the model.pi file.

Maybe you can help me jumping over that hurdle - many thanks! 
Florian

**Comment by flde** [comment]
Hi Adam, many thanks! I run the colab and realized that I set copy=True in setup_anndata without catching the output. With the standard installation that leads to a error when training the model but not the forked version. When copy=False both version work perfectly.

**Comment by adamgayoso** [comment]
We test all the latest code, so this would have appeared on our side. I think the issue is the pytorch lightning version, you should ensure it's between 1.5 and 1.6
