### ISSUE TITLE
Continuous covariate for batch in scVI

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#364]
In the original publication, s is supposed to be any type of random variable even though it is introduced with only batch effects. Unfortunately, the codebase only works for discrete values of s. There would be actually quite some changes involved as the batch id is transformed far inside the module into a one-hot 
https://github.com/YosefLab/scVI/blob/master/scvi/models/modules.py#L57

Being able to condition on a continuous, multi-dimensional measurement (which includes the discrete case if adding the onehot transformation) would be really useful for people in the YosefLab and the greater comp bio community.

**Comment by adamgayoso** [comment]
Should this not also be handled in #374 by adding another tensor in the data loader of continuous covariates?

**Comment by adamgayoso** [comment]
We are finally close to being able to implement one version of this based on our dataset refactoring. Essentially we will allow arbitrary numbers of categorical or continuous covariates, though only one "special" covariate will be available for correction in differential expression. `z` will be enforced to be invariant to all covariates.

@davemcg @vals do you have any datasets in mind that would be good to test and demonstrate this on?

**Comment by vals** [comment]
For Smart-seq data a reasonable covariate would be the number of detected genes. In many cases for Smart-seq the cDNA libraries are experimentally normalized (take a fixed mass of cDNA from each well), so you will lose the correlation between number of sequenced reads and number of detected genes.

I'm not sure of UMI droplet data with a priori known continuous covariates, you could imagine a high resolution drug dilution or a time series though. 

One idea could be spermatogenesis datasets. They have probably the most clear trajectories of any datasets I have seen. For example this https://www.nature.com/articles/s41422-018-0099-2  or this https://www.nature.com/articles/s41598-018-24725-0 ,  or this https://www.nature.com/articles/s41467-019-09182-1 . You could identify some kind of pseudotime with a first analysis. Then redo the analysis and regress that pseudotime out and see that you get discrete clusters of the biological replicates.

**Comment by adamgayoso** [comment]
Thanks @vals, we will take a look at this.
