### ISSUE TITLE
Misleading function name in Posterior.py

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scvi-tools#390]
The `update` function of the `Posterior` is not updating the Posterior object but is copying the Posterior and changes its data loader - which is the appropriate behavior.
However the name `update` suggests the modification is performed inplace.
https://github.com/YosefLab/scVI/blob/66cc63ead0d1a219f8d0ba1018d6f610f2b91679/scvi/inference/posterior.py#L117-L122

**The name of this function should be changed.** 

_Ideas_: 
- `copy_update`
- `with_new_data_loader` - such that the function is called with`my_posterior.with_new_data_loader(...)`

**Comment by romain-lopez** [comment]
copy_update ? does not matter much but thanks for catching that !

**Comment by adamgayoso** [comment]
I think we call it `update_data_loader(inplace)`, where inplace is a bool whether to copy or not.
