### ISSUE TITLE
Entropy batch mixing for n_batches>2

### ISSUE THREAD

**Issue by NRshka** [YosefLab/scvi-tools#558]
Is it relevant to add the ability to calculate the entropy batch mixing for a dataset with several batches as an averaged value between all pairs or pairwise dictionary?

**Comment by adamgayoso** [comment]
So we should probably implement the mixing=-KL(P||Q), where P is the local distribution of batches for a cell and Q is the global batch distribution. The negative KL has a maximum value of 0 which would be the best mixing.

I'm not sure when we will get to this, so feel free to make a PR!

We'd have to rewrite this function:

https://github.com/YosefLab/scVI/blob/6c9f43e3332e728831b174c1c1f0c9127b77cba0/scvi/inference/posterior_utils.py#L20-L27

**Comment by adamgayoso** [comment]
We have removed these sorts of metrics from the codebase for at least the near future.
