### ISSUE TITLE
write documentation and review notebook for Annotation with scANVI

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#624]
The documentation on readthedocs is not super helpful and the notebook is also not extremely explanatory. A case study on seed labelling would be much more suitable.

**Comment by cartal** [comment]
Is there a working notebook now for this? 

I'm happy to create one if given the basics on the method.

**Comment by romain-lopez** [comment]
Hi @cartal, so far we have an annotation notebook which is not extremely useful for biologists [1] as well as a repository for reproducing the results of the scANVI paper [2]. I think the plan for this issue is to work out one (or two if needed) tutorials for scANVI.

There are several functions / mode of scANVI utilization we would like to highlight. Here are some ideas:
+ demonstrate how to use the labelled_set and the unlabelled_set for scANVI training
+ application to seed labelling as well as transfer of annotation from one dataset to others

We are pushing more updates on a separate aspect of scANVI training (so that would be for later):
+ using scANVI for hierarchical labelling

I think that @galenxing created a notebook for seed labelling. @galenxing would you be able to share that with us, maybe we can use it as a starting point? I know you're working on something different right now.

**Comment by galenxing** [comment]
@cartal, hey, sorry just seeing this now!

Here is an updated example notebook for seed labeling: https://colab.research.google.com/drive/1RZHYhB2IAJao-XEXxW0ZLCV7wcSjrzVe

We're in the middle of refactoring scVI so this will be broken and fully refactored in the near future, but might be useful for now. 

Let me know if you have any questions!

**Comment by romain-lopez** [comment]
working on this now, will be released with the new API

**Comment by adamgayoso** [comment]
Hi @cartal, we have an alpha release of the new scvi-tools package. If you look at the new documentation page, you'll see we have a section for contributed tutorials. We'd be happy to accept a tutorial if you still wanted to make on.

[Here](https://scvi.readthedocs.io/en/latest/user_guide/notebooks/harmonization.html) is how to use the new scANVI. Note, you do not need the `scvi.set_seed(0)`  code as this now happens behind the scenes. We just haven't updated the notebooks yet.

**Comment by cartal** [comment]
Sure! I'd be happy to help. I'll get in touch with you once I have a proper notebook. 

Regards

**Comment by romain-lopez** [comment]
Hi there, I think this issue can be closed! also, is there a way to add the seed-labeling notebook to our tutorial list on scvi-tools.org?
