### ISSUE TITLE
automatic epochs number selection?

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#677]
We propose a "pre-defined" number of epochs as in the benchmarking paper by the Theis lab, as part of one recipe for example

**Comment by vals** [comment]
In case it's relevant, I've experienced that the training curve usually flattens out if I set number of epochs = 1e6 / number_of_cells. It's handy because for most datasets inference always takes 12 minutes, so it's very predictable.

**Comment by romain-lopez** [comment]
Great Valentine :) we proposed another yet very similar thing. I think the slight difference is that we max it out at 400 epochs (maybe the coefficient is also slightly different). 

I have an interest in setting up an easy way to reproduce the benchmarking for different variants of scVI so that we can modify the "public code" and make sure we get the same performance (at least for the latent space). We could for example compare the two epoch numbers (though it might not matter that much).
