### ISSUE TITLE
gimVI tutorial outdated -> bad results

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#682]
It looks like there is a discrepancy between the code used by Achille for his paper:
https://github.com/ANazaret/gimvi-reproducibility/blob/master/gimvi_reproduce_osm_fish.ipynb 

And the code on the tutorial that Achille wrote on the scVI codebase last summer 
https://scvi.readthedocs.io/en/stable/tutorials/gimvi.html

The value of the adversarial loss scale is 1 (probably too low) but it is 5 on the code for the paper. This caused bad benchmarking values on this paper https://www.biorxiv.org/content/10.1101/2020.05.08.084392v1.full.pdf where the authors used the code from the tutorial, which uses 1. This is the only discrepancy I could find quickly but it might make an impact. https://github.com/tabdelaal/SpaGE/blob/master/benchmark/osmFISH_Ziesel/gimVI/gimVI.py#L47

**Comment by adamgayoso** [comment]
It seems more likely the case to me that they called `trainer.train()` and the default was 20 epochs or something.

**Comment by romain-lopez** [comment]
Great catch, I had not seen this

**Comment by adamgayoso** [comment]
@ANazaret are up for checking that the tutorial uses the best defaults? And if you have extra time, it would be great to refactor lightly to make sure it works in Google Colab!

**Comment by adamgayoso** [comment]
@galenxing can you check the notebook above and ensure our GIMVI class uses the best defaults?

**Comment by romain-lopez** [comment]
Let's double check one last time and close this issue ASAP

**Comment by romain-lopez** [comment]
checked
