### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#746]
+ add another link to the references part of the docs on the index.html, on the bullet point "please consider citing the corresponding publication."
+ remove this line in the tutorial.html "When you execute the notebook yourself, please set your own save_path."
+ change the image for scVI, instead use a UMAP of a cool dataset, with cell type annotation (even PBMC is fine)
+ "Some are designed to work seamlessly in Google Colab, a free cloud computing platform." We need all of them to work in Colab now.
+ "Previous versions of the tutorials are available by changing the Read the Docs version (available at the bottom of the page)." Point to the version list of read the docs (the project page if I remember well)

**Comment by romain-lopez** [comment]
in the core.html page:
+ autotune should go under core.utils
+ differential expression as well
+ Early stopping as well
+ the abstract trainer class should just be under trainers and not trainers.trainer

**Comment by romain-lopez** [comment]
In the core.html page, after this warning

**The scvi.core top-level module is PRIVATE. We document here for contributors. Please use the top-level module scvi.models.**

and before this 

**Models**

We should add a description of what we have in the codebase. Primitives for training, models, VAEs, etc... and add a bit of text to make this page easier to parse

**Comment by adamgayoso** [comment]
Don't think this is relevant anymore.
