### ISSUE TITLE
What is the best branch to use at the moment? Dev_v1.0 or master or something else?

### ISSUE THREAD

**Issue by Cottoneyejoe95** [YosefLab/scvi-tools#769]
Hi Guys, I would like to know what branch is the best to use at the moment.

Best regards
Marco

**Comment by adamgayoso** [comment]
Sorry `dev_v1.0` should no longer be there. If you'd like to use `scvi-tools` please use `master`; otherwise if you're looking for the old scvi you can use the 0.6.8 tag.
