### ISSUE TITLE
Error when doing DE with latest pip version of scvi-tools

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#783]
Hi, I'm running into the following error when trying to do DE using the `model.differential_expression` function. The error is:  `ValueError: provided out is the wrong size for the reduction`

I have created a notebook that reproduces the error on colab:
https://colab.research.google.com/gist/Munfred/37c6a606e2ec6879dc8e17d74364c479/de-error-example-sep22.ipynb

The full traceback is below. 

Aditionally, I noticed that the `scvi.__version__` is missing. If I do:
```
import scvi
print(scvi.__version__)
```
It returns `None`.

Thanks

---

Full traceback:

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-d7b37e40fc13> in <module>()
      5     idx1=idx1,
      6     idx2=idx2,
----> 7     mode='change',
      8 )

7 frames
/usr/local/lib/python3.6/dist-packages/scvi/core/models/rnamixin.py in differential_expression(self, adata, groupby, group1, group2, idx1, idx2, mode, delta, batch_size, all_stats, batch_correction, batchid1, batchid2, **kwargs)
    202             delta,
    203             batch_correction,
--> 204             **kwargs,
    205         )
    206 

/usr/local/lib/python3.6/dist-packages/scvi/core/models/_utils.py in _de_core(adata, model_fn, groupby, group1, group2, idx1, idx2, all_stats, all_stats_fn, col_names, mode, batchid1, batchid2, delta, batch_correction, **kwargs)
     70 
     71         if all_stats is True:
---> 72             genes_properties_dict = all_stats_fn(adata, cell_idx1, cell_idx2)
     73             all_info = {**all_info, **genes_properties_dict}
     74 

/usr/local/lib/python3.6/dist-packages/scvi/model/_utils.py in scrna_raw_counts_properties(adata, idx1, idx2)
     35     data = get_from_registry(adata, _CONSTANTS.X_KEY)
     36     data1 = data[idx1]
---> 37     data2 = data[idx2]
     38     mean1 = np.asarray((data1).mean(axis=0)).ravel()
     39     mean2 = np.asarray((data2).mean(axis=0)).ravel()

/usr/local/lib/python3.6/dist-packages/scipy/sparse/_index.py in __getitem__(self, key)
     57                 return self._get_arrayXint(row, col)
     58             elif isinstance(col, slice):
---> 59                 return self._get_arrayXslice(row, col)
     60         else:  # row.ndim == 2
     61             if isinstance(col, INT_TYPES):

/usr/local/lib/python3.6/dist-packages/scipy/sparse/csr.py in _get_arrayXslice(self, row, col)
    323             col = np.arange(*col.indices(self.shape[1]))
    324             return self._get_arrayXarray(row, col)
--> 325         return self._major_index_fancy(row)._get_submatrix(minor=col)
    326 
    327 

/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py in _major_index_fancy(self, idx)
    688         idx_dtype = self.indices.dtype
    689         res_indptr = np.zeros(M+1, dtype=idx_dtype)
--> 690         np.cumsum(row_nnz[idx], out=res_indptr[1:])
    691 
    692         nnz = res_indptr[-1]

<__array_function__ internals> in cumsum(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in cumsum(a, axis, dtype, out)
   2468 
   2469     """
-> 2470     return _wrapfunc(a, 'cumsum', axis=axis, dtype=dtype, out=out)
   2471 
   2472 

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: provided out is the wrong size for the reduction
```

**Comment by adamgayoso** [comment]
I just released 0.7.0a5 earlier today that should have fixed this. I would try installing again. The fix to the __version__ is on for a6.

**Comment by adamgayoso** [comment]
If it didn't fix it, using a dense array for X (densify before setup anndata) will fix it.

**Comment by Munfred** [comment]
Converting X to dense fixes it. I've only been able to install v0.7.0a5 (or at least I think that the one) because that's the one on pip. I tried to install the latest version with `!pip install git+https://github.com/YosefLab/scvi-tools.git` on colab but that yields an error. Should I be installing from a different branch?

**Comment by adamgayoso** [comment]
Hmmmm actually this is a different issue than I thought. Was your matrix csr? csc? coo?

**Comment by adamgayoso** [comment]
Also, in colab, you need to first do

```
    !pip install --quiet --upgrade jsonschema
```

**Comment by Munfred** [comment]
The matrix format is CSR, the scipy version is 1.4.1, which turns out is the Colab default. So far I've only been running scvi-tools on Colab to get used to it because I have other code on the cluster I typically use that I don't want to rewrite yet. I upgraded the Colab scipy to 1.5.1 and reran the code and indeed that fixed the problem. 


Now I remember that a while back I had previously run into random errors with CSR matrices on scVI and if I recall correctly upgrading everything fixed them. 

The reason why I have these adatas in CSR format is because I read them from .mtx files in anndata using their `read_mtx` method, and that method uses the scipy CSR: 

https://github.com/theislab/anndata/blob/58886f09b2e387c6389a2de20ed0bc7d20d1b843/anndata/_io/read.py#L265-L283

**Comment by adamgayoso** [comment]
I think the issue has to do with it being a pandas series. I think I can fix that.
