### ISSUE TITLE
Error when saving h5ad

### ISSUE THREAD

**Issue by notimenocall** [YosefLab/scvi-tools#792]
I think this may be a bug and apologize if I miss anything. I am trying to save the adata (adata.write("...")) after running through the scvi pipeline and got this error. Deleting adata.uns['_scvi'] solves the issue.

```pytb
NotImplementedError: Failed to write value for uns/_scvi/categorical_mappings/_scvi_batch/mapping, since a writer for type <class 'pandas.core.indexes.base.Index'> has not been implemented yet.

Above error raised while writing key 'uns/_scvi/categorical_mappings/_scvi_batch/mapping' of <class 'h5py._hl.files.File'> from /.
```

**Comment by adamgayoso** [comment]
This looks like it is indeed an issue, thank you we will look into it.

**Comment by adamgayoso** [comment]
This has been fixed in the latest pip installable version.
