### ISSUE TITLE
subset data model and reproducibility

### ISSUE THREAD

**Issue by wangjiawen2013** [YosefLab/scvi-tools#803]
Dear,
It is said that It’s possible to also query a subset of the anndata (https://www.scvi-tools.org/en/latest/user_guide/notebooks/api_overview.html) after training the model. I trained the model on the full data. However, is it necessary to re-train the model when I use the subset data (for example, subsample cells according to specific markers)  ?

**Comment by wangjiawen2013** [comment]
Besides, I ran scvi_tools several times, but each time it had different latent values and different scvi_normalized values. What caused this case ? Could it be fixed for the purpose of reproducibility ?

**Comment by adamgayoso** [comment]
> However, is it necessary to re-train the model when I use the subset data (for example, subsample cells according to specific markers) ?

This question is more statistical in nature. Generally, you will not need to retrain, but it depends on the model fit, the size of the subpopulation, etc. I would think about it like PCA. Would you refit that?

> Besides, I ran scvi_tools several times, but each time it had different latent values and different scvi_normalized values. What caused this case ? Could it be fixed for the purpose of reproducibility ?

You can set the seed before model creation with `scvi.settings.seed = SEED`, `SEED = 0` for example. 
PyTorch, which underlies scvi-tools does not guarantee reproducibility across versions, so the seed will only be reproducible with respect to the same exact version of PyTorch. In general, scvi-tools models use stochastic optimization, so we should not expect two runs to yield the same results.
