### ISSUE TITLE
Loading models with correct adata in new API: option to save adata?

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#812]
Hello, with the new API when loading a model, it is necessary to provide it with an adata file. In the old API, saving a model would also save the adata and it would be loaded automatically. Because for doing the gene selection now I restrict my adata to the genes that I use, the most failsafe way tt not mixing up the genes is to save this new adata for loading at a later point. 

Saving and loading a model in the new API (as per the documentation) is done with these two lines:
```
model.save("my_model/")
model = scvi.model.SCVI.load(adata, "my_model/", use_cuda=True)
```

This creates the folder `my_model` which has two files: `model_params.pt` and `attr.pkl`. 

What I end up doing is I also save the adata in the `my_model` folder as something like `my_adata.h5ad`. Is there a better way of doing this? It is only two extra lines of code, but I sometimes forget and then I can't reload my model because the if a single gene is different in gene selection process (which is probabilistic). 

If saving a separate adata is the recommended strategy, is there a reason why `model.save` doesn't have an option to automatically save the adata? It would be convenient if there was a flag `save_adata=True` what would save `my_model/adata.h5ad`

Thanks!

**Comment by adamgayoso** [comment]
Sure, we can add that option!
