### ISSUE TITLE
Error when doing DE `AttributeError: 'NoneType' object has no attribute 'var_names'` from loaded model

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#816]
Hello, I ran into the error below when trying to do DE from a model that was loaded using these 3 lines:

```
adata=anndata.read('./'+ model_name+'.model/adata.h5ad')
model = scvi.model.SCVI.load(adata, model_name+'.model', use_cuda=True)
de = model.differential_expression( groupby="leiden")
```

After some poking around, I copied these lines from the intro example, and then the DE ran with no problem:
```
adata.layers["counts"] = adata.X.copy() # preserve counts
adata.raw = adata # freeze the state in `.raw`
```
However, I find it odd that I had to run these lines again, because the anndata that I saved was the one that used to train the model. I had not realized that having the adata itself stored in `adata.raw` was necessary, but given the error, this seems to be the case?

![image](https://user-images.githubusercontent.com/12504176/95141863-a445a700-0748-11eb-856c-88e457aba950.png)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-125-eb1e0fcfe1d1> in <module>
      1 de = model.differential_expression(
----> 2     groupby="leiden",
      3 )
      4 de.head()

~/anaconda3/lib/python3.7/site-packages/scvi/core/models/rnamixin.py in differential_expression(self, adata, groupby, group1, group2, idx1, idx2, mode, delta, batch_size, all_stats, batch_correction, batchid1, batchid2, **kwargs)
    179         adata = self._validate_anndata(adata)
    180 
--> 181         col_names = _get_var_names_from_setup_anndata(adata)
    182         model_fn = partial(
    183             self.get_normalized_expression,

~/anaconda3/lib/python3.7/site-packages/scvi/model/_utils.py in _get_var_names_from_setup_anndata(adata)
    119         adata.var_names
    120         if adata.uns["_scvi"]["use_raw"] is False
--> 121         else adata.raw.var_names
    122     )
    123 

AttributeError: 'NoneType' object has no attribute 'var_names'
```

**Comment by adamgayoso** [comment]
Could you print

```python
print(adata.uns["_scvi"]["use_raw"])
```

Right after you load your object?

**Comment by Munfred** [comment]
The adata setup was done (in another notebook) with these lines:
```
adata.layers["counts"] = adata.X.copy() # preserve counts
scvi.data.setup_anndata(adata, layer="counts", batch_key='experiment') 
```
So I did not do `adata.raw = adata` which seems to be the problem

Doing `print(adata.uns["_scvi"]["use_raw"])` returns `False`

print(adata.uns["_scvi"]["use_raw"])

<img width="951" alt="Screen Shot 2020-10-05 at 22 25 43" src="https://user-images.githubusercontent.com/12504176/95148471-c4319680-0759-11eb-8f04-4fb17ee727ba.png">

**Comment by galenxing** [comment]
Hi @Munfred, 

I'm trouble replicating this bug. Below is my code. Do you mind trying it out or posting the exact workflow that led to the error?

```
import scvi
adata = scvi.data.synthetic_iid()
adata.layers['counts'] = adata.X.copy()

scvi.data.setup_anndata(adata, layer="counts", batch_key='batch') 

model = scvi.model.SCVI(adata)
model.train(1)
model.save('tmp', overwrite=True)
model = scvi.model.SCVI.load(a, 'tmp')
model.differential_expression(groupby = 'batch')
```

Thanks!

**Comment by galenxing** [comment]
@Munfred 

Nevermind, I just found the bug.  It's caused by saving the anndata. It turns the boolean into type numpy.bool_, and thus `if adata.uns["_scvi"]["use_raw"] is False` will always evaluate to False. I will submit a PR to fix this. Thanks for letting us know!

To Reproduce: 
<img width="477" alt="Screen Shot 2020-10-06 at 7 51 24 PM" src="https://user-images.githubusercontent.com/9795194/95282086-85f5af00-080d-11eb-9d7f-0bb5c6e72d00.png">
