### ISSUE TITLE
AttributeError: module 'scvi' has no attribute 'data'

### ISSUE THREAD

**Issue by aralbright** [YosefLab/scvi-tools#824]
Hi, I've got my data to a point where I'd like to use scVI for batch correction, but for some reason it's not working properly. scVI by itself imports just fine, but I'm not sure why it's not recognizing any scvi functions. 

```python
scvi.data.setup_anndata(data, layer="raw")
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-294ac6c9fc9d> in <module>
----> 1 scvi.data.setup_anndata(data, layer="raw")

AttributeError: module 'scvi' has no attribute 'data'

```

#### Versions:

> scvi-tools 0.7.0a5  

Thanks! 

Ashley

**Comment by galenxing** [comment]
Hi @aralbright!

We changed the file structure on the backend when going from our alpha to beta release, so you'll need to upgrade scvi via: 

`pip install scvi-tools -U`

or 

`conda update scvi-tools`

depending on how you installed. 

Best,
Galen

**Comment by aralbright** [comment]
Thanks! I used pip to install it yesterday so I assumed everything was up to date, was this a _super_ recent change and I just got unlucky?

**Comment by galenxing** [comment]
Huh, thats weird, the latest version was released 9/28. But hopefully just running the upgrade commend should work then!

**Comment by aralbright** [comment]
It did, thanks! Running ```model.train()``` now :)

**Comment by slagtermaarten** [comment]
Hi, I'm currently experiencing the same problem. I have scvi-tools 7.1 (newest according to pip), any ideas? Thanks!

**Comment by galenxing** [comment]
@slagtermaarten Sorry to hear that! 

Can you provide the output of:
`import scvi; print(scvi.__version__)`

**Comment by slagtermaarten** [comment]
@galenxing Thanks for you quick reply!

I resolved the problem. Even though I had activated my new conda env, starting the python interpreter actually started a wrong version of python (3.7.6), in which I guess the old version of scvi was installed. If I start `python3.8` in a yet another newly created environment, I do manage to get past this step -- I get `scvi.__version__ == 7.1`

**Comment by galenxing** [comment]
@slagtermaarten Glad to hear!

**Comment by DRSEI** [comment]
> Hi, I've got my data to a point where I'd like to use scVI for batch correction, but for some reason it's not working properly. scVI by itself imports just fine, but I'm not sure why it's not recognizing any scvi functions.
> 
> ```python
> scvi.data.setup_anndata(data, layer="raw")
> ```
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-36-294ac6c9fc9d> in <module>
> ----> 1 scvi.data.setup_anndata(data, layer="raw")
> 
> AttributeError: module 'scvi' has no attribute 'data'
> ```
> 
> #### Versions:
> > scvi-tools 0.7.0a5
> 
> Thanks!
> 
> Ashley

Hello Everyone I am having the same issue. 

import scvi; print(scvi.__version__)  0.15.2

scvi.data.setup_anndata(adata, layer="counts", batch_key='tissueType')


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-97-c7838b8d7080>](https://localhost:8080/#) in <module>()
      1 # tell scvi where to get the data
----> 2 scvi.data.setup_anndata(adata, layer="counts", batch_key='tissueType')

AttributeError: module 'scvi.data' has no attribute 'setup_anndata'


I have updated the package but I am unable to resolve the problem.

**Comment by DRSEI** [comment]
hi @adamgayoso  Thank you so much

**Comment by bigtimecodersean** [comment]
Hey guys, I am running into a similar issue. I am trying to run the introductory tutorial: https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html

I am getting stuck on loading the data in the Colab tutorial. Keep getting the error that:

"module 'scvi' has no attribute 'data'"

when I run: 

"adata = scvi.data.heart_cell_atlas_subsampled()"

Anything / dependencies that I might be missing ?

**Comment by bigtimecodersean** [comment]
To add one additional variable to the above ^. Throughout my code, in the first few cells of the tutorial, I am getting the message:

 WARNING: Ignoring invalid distribution -orch (/usr/local/lib/python3.7/dist-packages)

**Comment by adamgayoso** [comment]
@bigtimecodersean how did you install scvi-tools?

**Comment by bigtimecodersean** [comment]
Thanks for the quick response. 
I tried installing scvi and scvi-tools today using 

pip install scvi 
pip install scv -U
pip install scvi-tools

**Comment by adamgayoso** [comment]
Please install using the instructions [here](https://docs.scvi-tools.org/en/stable/installation.html). Specifically, do not use `pip install scvi` as this is an old unmaintained package.

**Comment by royfrancis** [comment]
I am confused. Do we need both scvi and scvi-tools? The [installation page](https://docs.scvi-tools.org/en/stable/installation.html) only mentions scvi-tools but [other pages](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html) mentions `import scvi`. Does `import scvi` import `scvi-tools`?

```
>>> import scvi
>>> scvi.model.SCVI.setup_anndata(adata, layer="counts", categorical_covariate_keys="donor_id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scvi' has no attribute 'model'

>>> scvi.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scvi' has no attribute '__version__'
```

**Comment by adamgayoso** [comment]
installing scvi-tools allows `import scvi`. This would be similar for scikit-learn and `sklearn`. 

The old `scvi` package that you see is a previous iteration of this work that you *do not* want

**Comment by royfrancis** [comment]
Ok. I have removed scvi and only have scvi-tools. I still get this error: 

```
>>> scvi.model.SCVI.setup_anndata(adata, layer="counts", categorical_covariate_keys="donor_id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scvi' has no attribute 'model'
```

**Comment by royfrancis** [comment]
Hmm.. I see that my scvi-tools version is **0.8.1** while [conda](https://anaconda.org/conda-forge/scvi-tools) seems to have **0.20.1**. Perhaps that's why. And for me, conda refuses to update this package. Possibly conflicting with some other package.

**Comment by hongruhu** [comment]
similar issue when I ran `scvi.model.SCVI.setup_anndata(adata_concat, layer="counts", batch_key="batch")`
the error is `AttributeError: module 'scvi' has no attribute '__version__'`
`scvi.__version__ = '0.20.3'`

**Comment by adamgayoso** [comment]
@hongruhu can you provide the full traceback?

**Comment by hongruhu** [comment]
@adamgayoso here you go, thanks!
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [169], in ()
----> 1 scvi.model.SCVI.setup_anndata(adata_concat, layer="counts")

File [/share/miniconda3/envs/tangram/lib/python3.8/site-packages/scvi/model/_scvi.py:208](https://file+.vscode-resource.vscode-cdn.net/share/miniconda3/envs/tangram/lib/python3.8/site-packages/scvi/model/_scvi.py:208), in SCVI.setup_anndata(cls, adata, layer, batch_key, labels_key, size_factor_key, categorical_covariate_keys, continuous_covariate_keys, **kwargs)
    206 if adata_minify_type is not None:
    207     anndata_fields += cls._get_fields_for_adata_minification(adata_minify_type)
--> 208 adata_manager = AnnDataManager(
    209     fields=anndata_fields, setup_method_args=setup_method_args
    210 )
    211 adata_manager.register_fields(adata, **kwargs)
    212 cls.register_manager(adata_manager)

File [/share/miniconda3/envs/tangram/lib/python3.8/site-packages/scvi/data/_manager.py:87](https://file+.vscode-resource.vscode-cdn.net/share/miniconda3/envs/tangram/lib/python3.8/site-packages/scvi/data/_manager.py:87), in AnnDataManager.__init__(self, fields, setup_method_args, validation_checks)
     84 self.fields = fields or []
     85 self.validation_checks = validation_checks or AnnDataManagerValidationCheck()
     86 self._registry = {
---> 87     _constants._SCVI_VERSION_KEY: scvi.__version__,
     88     _constants._MODEL_NAME_KEY: None,
     89     _constants._SETUP_ARGS_KEY: None,
     90     _constants._FIELD_REGISTRIES_KEY: defaultdict(dict),
     91 }
     92 if setup_method_args is not None:
     93     self._registry.update(setup_method_args)

AttributeError: module 'scvi' has no attribute '__version__'```

**Comment by adamgayoso** [comment]
@hongruhu how did you install scvi? Do you happen to be in a python file called scvi.py?

**Comment by hongruhu** [comment]
@adamgayoso I did pip install and I could print `scvi.__version__`

**Comment by ShaowenJ** [comment]
@Agamart Hi, I am encountering the same issue, how did you solve this previously?

**Comment by canergen** [comment]
Hi, this points to a wrong installation. Can you share your Python version and whether you followed our tutorials to install scVI-tools. Please also provide the exact error message.

**Comment by emdann** [comment]
This issue still lives. 

Just trained a model, loading with 
```python
model = scvi.model.SCVI.load(model_path)
``` 
throws
```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 model = scvi.model.SCVI.load(f"{data_dir}/{dataset_name}_model_scvi/")

File /oak/stanford/groups/pritch/users/emma/miniforge3/envs/perturb-vs-tissue-env/lib/python3.10/site-packages/scvi/model/base/_base_model.py:706, in BaseModelClass.load(cls, dir_path, adata, accelerator, device, prefix, backup_url)
    702 # Calling ``setup_anndata`` method with the original arguments passed into
    703 # the saved model. This enables simple backwards compatibility in the case of
    704 # newly introduced fields or parameters.
    705 method_name = registry.get(_SETUP_METHOD_NAME, "setup_anndata")
--> 706 getattr(cls, method_name)(adata, source_registry=registry, **registry[_SETUP_ARGS_KEY])
    708 model = _initialize_model(cls, adata, attr_dict)
    709 model.module.on_load(model)

File /oak/stanford/groups/pritch/users/emma/miniforge3/envs/perturb-vs-tissue-env/lib/python3.10/site-packages/scvi/model/_scvi.py:218, in SCVI.setup_anndata(cls, adata, layer, batch_key, labels_key, size_factor_key, categorical_covariate_keys, continuous_covariate_keys, **kwargs)
    216 if adata_minify_type is not None:
    217     anndata_fields += cls._get_fields_for_adata_minification(adata_minify_type)
--> 218 adata_manager = AnnDataManager(fields=anndata_fields, setup_method_args=setup_method_args)
    219 adata_manager.register_fields(adata, **kwargs)
    220 cls.register_manager(adata_manager)

File /oak/stanford/groups/pritch/users/emma/miniforge3/envs/perturb-vs-tissue-env/lib/python3.10/site-packages/scvi/data/_manager.py:94, in AnnDataManager.__init__(self, fields, setup_method_args, validation_checks)
     91 self.fields = fields or []
     92 self.validation_checks = validation_checks or AnnDataManagerValidationCheck()
     93 self._registry = {
---> 94     _constants._SCVI_VERSION_KEY: scvi.__version__,
     95     _constants._MODEL_NAME_KEY: None,
     96     _constants._SETUP_ARGS_KEY: None,
     97     _constants._FIELD_REGISTRIES_KEY: defaultdict(dict),
     98 }
     99 if setup_method_args is not None:
    100     self._registry.update(setup_method_args)

AttributeError: module 'scvi' has no attribute '__version__'
```

But `scvi.__version__` works fine when I run it (`1.1.3`).

This is with Python 3.10.14 and installing scvi-tools with `pip install scvi-tools`.

**Comment by canergen** [comment]
Hi, have you modified the code? Sometimes when I modify code, the version is not correctly loaded. Another problem is jupyter notebooks autoreload that can throw these problems. Otherwise, how have you installed scvi-tools?

**Comment by emdann** [comment]
No autoreload or changes to the code here. 

I installed on a conda env running:
```
pip install scvi-tools
```

**Comment by canergen** [comment]
This is weird. Is it dependent on loading this specific model and can you initialize a model without problems and afterwards load it?
