### ISSUE TITLE
Is it possible to retrieve expression value of other genes after batch correction

### ISSUE THREAD

**Issue by wangmhan** [YosefLab/scvi-tools#828]
Hi, during the batch correction I used only highly variable genes as suggested.
But I'm also interested in expression of rest genes. Is it possible to get corrected expression of those unused genes?

Big thanks!

```python
[CODE HERE]
```

**Comment by adamgayoso** [comment]
This is not possible unfortunately. You will have to train the model with all the genes you are interested in.
