### ISSUE TITLE
Support for either CSC or CSR?

### ISSUE THREAD

**Issue by vals** [YosefLab/scvi-tools#835]
Sparse matrices are currently cast to CSR matrices when setting up the anndata.

Would it be possible to optionally support CSC format?

I am often doing downstream analysis of the AnnData files with Julia, which for some reason only supports CSC matrices. Currently I need to convert adata.X to CSC and save a copy of adata for analysis with Julia. It would make my data organization a bit easier if scVI could also work on CSC matrices.

**Comment by adamgayoso** [comment]
I think the issue was that CSC was slower for the row slicing used in minibatching. We could double check this.
