### ISSUE TITLE
DE progress bar breaks print statements if running inside loops in notebooks

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#839]
If I put a call for the DE function `model.differential_expression` inside a for loop with other print statements, they don't show up on the notebook output, as in the example screenshot below. The progress bar always shows 0% because there is only one comparison done per function call.

In this case I decided to try paiwise DE between all of 20 clusters, and I wanted to have the print statement to know the progress, since the DE progress bar only works if you call the function only once and gets reset between calls.

This is not a big deal, but is there a workaround?

![image](https://user-images.githubusercontent.com/12504176/97029181-737cb480-1533-11eb-98f3-cf7b10f11eeb.png)

**Comment by galenxing** [comment]
@Munfred, hey if you update to the newest version of scvi-tools, it should fix this. It was because we updated the progress bar library. The newest version defaults back to tqdm as our progress bar.
