### ISSUE TITLE
Broken Colab links in some of the tutorials

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#840]
I was going through the tutorials page and noticed that some of the "open in colab" icon links are broken. Here's the list of tutorials and what I found, two links are broken:

https://www.scvi-tools.org/en/stable/user_guide/notebooks/api_overview.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi_tutorials/blob/master/api_overview.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/data_loading.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/data_loading.ipynb

https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/data_loading.ipynb
Link works:   
https://colab.research.google.com/github/yoseflab/scvi_tutorials/blob/master/totalVI.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/harmonization.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/harmonization.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/linear_decoder.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/linear_decoder.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/cite_scrna_integration_w_totalVI.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/cite_scrna_integration_w_totalVI.ipynbv

https://www.scvi-tools.org/en/stable/user_guide/notebooks/gimvi_tutorial.html
Link is BROKEN, currently pointing to: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/dev/gimvi_tutorial.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/AutoZI_tutorial.html
Link works: 
https://colab.research.google.com/github/yoseflab/scvi-tutorials/blob/master/AutoZI_tutorial.ipynb

https://www.scvi-tools.org/en/stable/user_guide/notebooks/contributed/scVI_DE_worm.html
Link is BROKEN, currently pointing to: 
https://colab.research.google.com/github/yoseflab/scvi/blob/stable/docs/contributed_tutorials/scVI_DE_worm.ipynb

**Comment by adamgayoso** [comment]
Thanks for reporting this. We’ll fix it in the next release.

**Comment by adamgayoso** [comment]
I figured out how to automate the link creation, so it'll be fixed once 0.8.0 is released. If you're curious, you can checkout the latest version of the docs.
