### ISSUE TITLE
How to use pretrained_model parameter in scANVI

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/scvi-tools#847]
I want to use scANVI with label transfer. I noticed that it has parameter pretrained_model and I was wondering it this can be used to reduce time of running.
I would like to use it in the following way. Please let me know if this is the intended use:
I have reference dataset - I want to train scVI on this data and use it as pretrained_model.
I have a query that does not have annotation. So If I understand correctly  I should then provide to scANVI the pretrained model + concatenated adata (ref+query, this time with labels).
When I do predict can I use just query data?
Must I register each dataset separately to scVI?  E.g. one for loading model (ref only, including cells I will not use for label transfer), one for compiling model/scANVI (ref - only cells with annotation + query),  and one for prediction?
Do I still need to run train on scANVI if I give it pretrained model as input?

**Comment by adamgayoso** [comment]
Sorry for the delay. Scanvi by default is created from a pretrained scvi model (that is pretrained on labelled and unlabelled data). The intention of this argument is to allow you to train an SCVI class model of both sets of cells and then build the scanvi classification mechanisms on top of that.

**Comment by adamgayoso** [comment]
Closing for now, but please let me know if you have any trouble with this argument.
