### ISSUE TITLE
High variable genes

### ISSUE THREAD

**Issue by wangjiawen2013** [YosefLab/scvi-tools#850]
Hi,
I notice that new released scvi uses only high variable genes, while the earlier version (0.4.1) used all the genes in it's original tutorial. I used v0.41. to process my single data last year. So, does the change have a major influence ?

**Comment by adamgayoso** [comment]
Did you use the old subsample genes method in 0.4.1? The model has not fundamentally changed at all, just the interface. If you'd like to run with all genes you are welcome to do that, though we have found gene selection can give better clustering results, etc.

**Comment by wangjiawen2013** [comment]
According to scanpy's tutorial, the result of the highly-variable-genes detection is stored as an annotation in .var.highly_variable and auto-detected by PCA and hence, sc.pp.neighbors and subsequent manifold/graph tools. In that case, the step actually do the filtering below is unnecessary, too.
I notice that scvi-tools select highly variable genes actually
    sc.pp.highly_variable_genes(
    adata,
    n_top_genes=2000,
    subset=True,
    layer="counts",
    flavor="seurat_v3"
)
In this case, lots of genes will be discard, because we can only store one matrix(either counts or normalized data et al) in the .raw attribute of AnnData object for later use in differential testing and visualizations of gene expression. So how can we keep all the genes in scvi pipeline ?

**Comment by wangjiawen2013** [comment]
Hi,
Please refer to this related issue:
https://github.com/10XGenomics/cellranger/issues/108#issuecomment-758455901
what about the scVI latent space ? Will genes with little variance contribute much to the latent space (just like principal components) ?
