### ISSUE TITLE
Training continuation

### ISSUE THREAD

**Issue by swbiggs4** [YosefLab/scvi-tools#853]
I wanted to ask about resuming training with a scVI model (or any model really). In PyTorch, one generally needs both the checkpointed model as well as the optimizer state to resume training. When loading a previously trained scVI model, does it also load the optimizer state such that you would be able to continue training?

Thanks in advance.

**Comment by adamgayoso** [comment]
This is not currently possible. We are currently migrating to pytorch lightning, which makes this fairly easy, and we are still working on whether this feature will be available at first.

**Comment by adamgayoso** [comment]
Just saw you posted on our discourse! We can move the conversation there.

**Comment by swbiggs4** [comment]
@adamgayoso thanks, makes sense.
