### ISSUE TITLE
NB theta = Gamma shape in Gamma-Poisson mixture?

### ISSUE THREAD

**Issue by vitkl** [YosefLab/scvi-tools#856]
Hi scVI team!

I am trying to understand the parameterization of NB distribution which you are using in:
https://github.com/YosefLab/scvi-tools/blob/e7704e402ed2243160f983d87cf78f660c7d9982/scvi/core/distributions/_negative_binomial.py

My understanding is that the parameter you call `theta` is the shape of Gamma distribution in Gamma-Poisson mixture (and is also called 'total count' in PyTorch). Is this correct?

<img width="611" alt="Screenshot 2020-11-15 at 16 33 30" src="https://user-images.githubusercontent.com/22567383/99190761-5d43cc00-2760-11eb-91ae-abb1468aa0eb.png">

Thanks

Vitalii

**Comment by adamgayoso** [comment]
This is accurate!

**Comment by vitkl** [comment]
Thanks Adam! Maybe you could add a note to your documentation clarifying
this?

**Comment by adamgayoso** [comment]
We will add this. Also, I'd have to double check the usage of `total_count` and `probs`. We actually never use these parameters in our models, but made them available in the distribution, where they appear to be converted to the mu, theta parameterization.
