### ISSUE TITLE
Silent mode for `differential_expression`

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#863]
I saw that both `poisson_gene_selection` and the `Trainer` class have an option `silent` that if True disables the progress bar.

Would it be possible to add this option to the `differential_expression` function? 

When looping through a custom combination of clusters sometimes I would prefer to disable it to prevent cluttering the output as in the picture below.

![image](https://user-images.githubusercontent.com/12504176/100759216-219b3a00-33cf-11eb-9a33-387e500b2b44.png)

**Comment by adamgayoso** [comment]
Yes we should add this, perhaps for now you can use the ipython magic `%%capture`?

**Comment by Munfred** [comment]
Good idea!
