### ISSUE TITLE
Training VAE model using continuous covariates returns numpy error

### ISSUE THREAD

**Issue by isaacg322** [YosefLab/scvi-tools#866]
Hello, I'm trying to run totalVI with my citeseq data. This consists of 5 batches for which I would like to consider the total number of features detected as an additional categorical covariate. During the scvi setup, I supply the key to this column in the sc.obs as: 

scvi.data.setup_anndata(andanta_sc, batch_key="sample", continuous_covariate_keys=["nFeature_RNA"], protein_expression_obsm_key="protein_expression", layer="counts")

Everything runs to the above point. However, when I run the vae setup command : scvi.model.TOTALVI(andanta_sc, use_cuda=False, latent_distribution="normal")

I get the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/scvi-env/lib/python3.7/site-packages/scvi/model/totalvi.py", line 94, in __init__
    super(TOTALVI, self).__init__(adata, use_cuda=use_cuda)
  File "/home/jovyan/my-conda-envs/scvi-env/lib/python3.7/site-packages/scvi/core/models/base.py", line 34, in __init__
    self._validate_anndata(adata, copy_if_view=False)
  File "/home/jovyan/my-conda-envs/scvi-env/lib/python3.7/site-packages/scvi/model/totalvi.py", line 1028, in _validate_anndata
    adata = super()._validate_anndata(adata, copy_if_view)
  File "/home/jovyan/my-conda-envs/scvi-env/lib/python3.7/site-packages/scvi/core/models/base.py", line 94, in _validate_anndata
    _check_anndata_setup_equivalence(self.scvi_setup_dict_, adata)
  File "/home/jovyan/my-conda-envs/scvi-env/lib/python3.7/site-packages/scvi/data/_utils.py", line 194, in _check_anndata_setup_equivalence
    if not _scvi_dict["extra_continuous_keys"].equals(target_cont_keys):
AttributeError: 'numpy.ndarray' object has no attribute 'equals'

I guess that this has to do with the processing of the covariate keys, as if I remove the "continuous_covariate_keys" from the scvi setup, then I'm able to setup the vae model.

Would you have any recommendations to solve the issue?

I'm running in Python 3.7.9, linux, using the environment recommended in the installation section from the SCVI-tools documentation at https://www.scvi-tools.org/en/stable/installation.html.

**Comment by adamgayoso** [comment]
> I guess that this has to do with the processing of the covariate keys, as if I remove the "continuous_covariate_keys" from the scvi setup, then I'm able to setup the vae model.

Sorry for the confusion, we do not yet support extra continuous/categorical covariates despite the ability to set them up -- if you'd like to try our development version, please install from the `pytorch_lit` branch.

**Comment by bjstewart1** [comment]
Getting the same problem.
Are you going to enable the use of covariates in the model training? What are the barriers to this at the moment?

**Comment by adamgayoso** [comment]
We are going through a major backend refactor in order to create an API to build new models. This is all on the pytorch_lit branch, and you should be able to view the docs from this branch at the bottom of the relevant PR. TotalVI is ready to go on that branch.

**Comment by adamgayoso** [comment]
Closing this issue. We have the code working on the `master` branch and we will release an alpha through pypi soon.
