### ISSUE TITLE
ValueError: Making .obs["type"] categorical failed. Expected categories:

### ISSUE THREAD

**Issue by zaidahmad23** [YosefLab/scvi-tools#867]
Hi there! I was attempting to use scanvi for cluster annotation transfer and I came across this issue
![Screen Shot 2020-12-11 at 9 09 50 PM](https://user-images.githubusercontent.com/70536206/101975928-41afd200-3bf5-11eb-9dd5-d05b4f75415f.png)

It seems as if the categories are the same (except for the commas?) so I'm kind of confused about where I'm going wrong. 
Thanks for taking a look at this!

**Comment by adamgayoso** [comment]
This issue could be that there are nan's in `.obs["type"]`? It should work if you give unlabeled cells a string category like "unknown".

**Comment by zaidahmad23** [comment]
Yup, that fixed everything. Thanks!
