### ISSUE TITLE
scANVI and batch correction

### ISSUE THREAD

**Issue by zaidahmad23** [YosefLab/scvi-tools#868]
Hi all, I had a quick question about using scANVI and batch correction. Is it best to do batch correction with a method like bbknn before or after running the scANVI model? Thanks!

**Comment by adamgayoso** [comment]
scANVI is designed to also perform batch correction -- all you need to do is register the batch key with scvi-tools during `setup_anndata`.

We would also very much appreciate if these types of questions were asked at https://discourse.scvi-tools.org/ in the future, so we can amass a knowledge base for other users. Thanks! :)

**Comment by zaidahmad23** [comment]
Will do from now on, thanks so much!
