### ISSUE TITLE
Model loading error between `0.7.1` and `0.8.0b0`

### ISSUE THREAD

**Issue by jacobkimmel** [YosefLab/scvi-tools#870]
Loading a model saved using `scvi-tools==0.7.1` in `scvi-tools==0.8.0b0` fails due to a change in layer names.
It looks like `fc_layers.Layer_{PARAM}` was changed to `fc_layers.Layer {PARAM}` (note swapping underscore for whitespace).

Eyeballing the model state dicts, it looks like a few other parameter names have been swapped as well (e.g. some now omit `.0`).

I'm pretty sure this can be fixed with some keyword checks and conversions inside the `load(...)` function specified in `scvi.core.models.base`, but I'm not sure if the breaking change was intentional and worth a PR to maintain compatibility.

e.g. adding this block before `model.model.load_state_dict(model_state_dict)` in `load()` fixes the issue.

```python
        # substitute "_" for " " in model_state_dict names
        # for compatibility with models save using `scvi-tools` <=0.7
        
        model_state_dict = {
            k.replace(" ", "_"):v for k, v in model_state_dict.items()
        }
        keys2swap = {
            "decoder.px_scale_decoder.weight": "decoder.px_scale_decoder.0.weight",
            "decoder.px_scale_decoder.bias": "decoder.px_scale_decoder.0.bias"
        }
        for new_key, old_key in keys2swap.items():
            model_state_dict[new_key] = model_state_dict[old_key]
            del model_state_dict[old_key]
```

```python
# load a `scvi.model.SCVI` model saved in `0.7.1`
vae = scvi.model.SCVI(adata)
vae = vae.load(
    saved_model_path,
    adata=adata,
)
```

```pytb
RuntimeError: Error(s) in loading state_dict for VAE:
	Missing key(s) in state_dict: "z_encoder.encoder.fc_layers.Layer_0.0.weight", "z_encoder.encoder.fc_layers.Layer_0.0.bias", "z_encoder.encoder.fc_layers.Layer_0.1.weight", "z_encoder.encoder.fc_layers.Layer_0.1.bias", "z_encoder.encoder.fc_layers.Layer_0.1.running_mean", "z_encoder.encoder.fc_layers.Layer_0.1.running_var", "l_encoder.encoder.fc_layers.Layer_0.0.weight", "l_encoder.encoder.fc_layers.Layer_0.0.bias", "l_encoder.encoder.fc_layers.Layer_0.1.weight", "l_encoder.encoder.fc_layers.Layer_0.1.bias", "l_encoder.encoder.fc_layers.Layer_0.1.running_mean", "l_encoder.encoder.fc_layers.Layer_0.1.running_var", "decoder.px_decoder.fc_layers.Layer_0.0.weight", "decoder.px_decoder.fc_layers.Layer_0.0.bias", "decoder.px_decoder.fc_layers.Layer_0.1.weight", "decoder.px_decoder.fc_layers.Layer_0.1.bias", "decoder.px_decoder.fc_layers.Layer_0.1.running_mean", "decoder.px_decoder.fc_layers.Layer_0.1.running_var", "decoder.px_scale_decoder.weight", "decoder.px_scale_decoder.bias". 
	Unexpected key(s) in state_dict: "z_encoder.encoder.fc_layers.Layer 0.0.weight", "z_encoder.encoder.fc_layers.Layer 0.0.bias", "z_encoder.encoder.fc_layers.Layer 0.1.weight", "z_encoder.encoder.fc_layers.Layer 0.1.bias", "z_encoder.encoder.fc_layers.Layer 0.1.running_mean", "z_encoder.encoder.fc_layers.Layer 0.1.running_var", "z_encoder.encoder.fc_layers.Layer 0.1.num_batches_tracked", "l_encoder.encoder.fc_layers.Layer 0.0.weight", "l_encoder.encoder.fc_layers.Layer 0.0.bias", "l_encoder.encoder.fc_layers.Layer 0.1.weight", "l_encoder.encoder.fc_layers.Layer 0.1.bias", "l_encoder.encoder.fc_layers.Layer 0.1.running_mean", "l_encoder.encoder.fc_layers.Layer 0.1.running_var", "l_encoder.encoder.fc_layers.Layer 0.1.num_batches_tracked", "decoder.px_decoder.fc_layers.Layer 0.0.weight", "decoder.px_decoder.fc_layers.Layer 0.0.bias", "decoder.px_decoder.fc_layers.Layer 0.1.weight", "decoder.px_decoder.fc_layers.Layer 0.1.bias", "decoder.px_decoder.fc_layers.Layer 0.1.running_mean", "decoder.px_decoder.fc_layers.Layer 0.1.running_var", "decoder.px_decoder.fc_layers.Layer 0.1.num_batches_tracked", "decoder.px_scale_decoder.0.weight", "decoder.px_scale_decoder.0.bias". 
```

#### Versions:

> 0.8.0b0

**Comment by adamgayoso** [comment]
I think this was a bit of oversight on my part. This would allow loading into 0.8.X., but there still is a edge case in the sense that our default is to now use the observed library size, which would only affect model retrain after load. 

On the other hand, we can add this functionality and add a warning about this. Though I'm not sure this is something we'd like in the codebase permanently. 

Given the simplicity of changing the keynames, what if we put a little utility function somewhere on our discourse site and made sure to reference it in the release notes?

**Comment by jacobkimmel** [comment]
> Given the simplicity of changing the keynames, what if we put a little utility function somewhere on our discourse site and made sure to reference it in the release notes?

This seems like a good solution to me.

Something like `.utils.backwards_compat_model_load(saved_model_path)` could go in and swap the key names, siloing the logic in a utility.
There are pluses / minuses to changing the keys on disk rather than dynamically in `load()` (pro: silos the logic, allows run-once updating of existing weights within a project; con: breaks loading with `<0.8.x`), so I have no strong opinion there.

It does seem important to preserve some means of loading older weights for research continuity without the user editing the keys manually though.
I think a fair number of `scvi` users probably aren't familiar enough with `torch` to debug that `RuntimeError` without non-trivial searching.

**Comment by adamgayoso** [comment]
I'll talk to @galenxing and we will figure something out, the util could very well work.

I'm surprised about px_scale decoder though because I didn't change that line of code as far as I know, it's still `nn.Linear`

**Comment by jacobkimmel** [comment]
> I'll talk to @galenxing and we will figure something out, the util could very well work.

Awesome 👍 

> Edit: Whoops, I did. I'll actually first see if I can undo these changes.

Fewer changes is probably parsimonious, but as long as there's logic to allow compatibility I think most users (& me!) will be well served.

Thanks for helping build a great tool!

**Comment by adamgayoso** [comment]
I was able to revert these changes, so no need for the util. However, we have some breaking changes for TOTALVI and SCANVI that were unavoidable.
