### ISSUE TITLE
hidden layers number and dispersion

### ISSUE THREAD

**Issue by wangjiawen2013** [YosefLab/scvi-tools#878]
Hi,
What's the best number of hidden layers used for encoder and decoder NNs and dispersion setting?
Namely, n_layers and dispersion parameter in scvi.model.scvi() when several batches are used.
scvi0.6.8 used 2 hidden layers and 30 latent space in https://www.scvi-tools.org/en/0.6.8/tutorials/harmonization.html
vae = VAE(all_dataset.nb_genes, n_batch=all_dataset.n_batches, n_labels=all_dataset.n_labels, n_hidden=128, n_latent=30, n_layers=2, dispersion='gene'). It seems that the default settings have changed now in scvi.model.scvi().

**Comment by adamgayoso** [comment]
The default settings have actually not changed, we just used non-default in that tutorial. These settings are perfectly reasonable to use (the non-default ones) and are actually the parameters used in a recent benchmarking study.
