### ISSUE TITLE
continuous_covariate error

### ISSUE THREAD

**Issue by notimenocall** [YosefLab/scvi-tools#882]
Hi,
Thank you for the continuous great work!
I ran into an error with `model = scvi.model.SCVI(adata)`. It fails when I added the continuous covariate
`scvi.data.setup_anndata(adata, batch_key = 'batch', layer="counts",
                        continuous_covariate_keys = ['percent.mt', 'nCount_RNA'])` 

Below is the error message. Thanks in advance!
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-70e2c3140ea4> in <module>
----> 1 model = scvi.model.SCVI(adata)

/sbgenomics/workspace/pkgs/lib/python3.8/site-packages/scvi/model/scvi.py in __init__(self, adata, n_hidden, n_latent, n_layers, dropout_rate, dispersion, gene_likelihood, latent_distribution, use_cuda, **model_kwargs)
     74         **model_kwargs,
     75     ):
---> 76         super(SCVI, self).__init__(adata, use_cuda=use_cuda)
     77         self.model = VAE(
     78             n_input=self.summary_stats["n_vars"],

/sbgenomics/workspace/pkgs/lib/python3.8/site-packages/scvi/core/models/base.py in __init__(self, adata, use_cuda)
     35             self.scvi_setup_dict_ = adata.uns["_scvi"]
     36             self.summary_stats = self.scvi_setup_dict_["summary_stats"]
---> 37             self._validate_anndata(adata, copy_if_view=False)
     38 
     39         self.is_trained_ = False

/sbgenomics/workspace/pkgs/lib/python3.8/site-packages/scvi/core/models/base.py in _validate_anndata(self, adata, copy_if_view)
     95             )
     96 
---> 97         _check_anndata_setup_equivalence(self.scvi_setup_dict_, adata)
     98 
     99         return adata

/sbgenomics/workspace/pkgs/lib/python3.8/site-packages/scvi/data/_anndata.py in _check_anndata_setup_equivalence(adata_source, adata_target)
   1167             raise ValueError('extra_continuous_keys not in adata.uns["_scvi"]')
   1168         target_cont_keys = adata.uns["_scvi"]["extra_continuous_keys"]
-> 1169         if not _scvi_dict["extra_continuous_keys"].equals(target_cont_keys):
   1170             raise ValueError(
   1171                 "extra_continous_keys are not the same between source and target"

AttributeError: 'numpy.ndarray' object has no attribute 'equals'`

**Comment by adamgayoso** [comment]
Hi @notimenocall -- sorry this should be more clear, but this feature won't be fully available until the next major release (< 1 month hopefully)

**Comment by notimenocall** [comment]
Thanks. Excited to know it is coming!

**Comment by adamgayoso** [comment]
Yes! And we have some examples showing how well it can work.
