### ISSUE TITLE
Imbalance dataset

### ISSUE THREAD

**Issue by farnoush-shh** [YosefLab/scvi-tools#896]
Hi,

I am using scArches to create and update  our reference dataset and since I am using semisupervised SCANVI model, I think I must ask my question here.

My question is about training on imbalance dataset.
Should I use other techniques to balance my dataset or this model has an option like 'focal loss' that I can use or...?

grateful for your suggesstion.

**Comment by galenxing** [comment]
Hi @farnoush-shh! If you are on our master branch, we just added an `n_samples_per_label` argument to the train method of scanvi. If set, then each epoch, it will subsample the number of cell used to train per label class. If a class has fewer than `n_samples_per_label` it will just use all the cells in that that class for each epoch. 

Soon, we might also add support for weighted sampling each epoch (#883)

**Comment by galenxing** [comment]
@farnoush-shh, I just wanted to add, we haven't fully tested this new subsampling scheme. In the paper, the authors just subsample the number of labeled training examples prior to training which is something worth trying as well.

**Comment by farnoush-shh** [comment]
@galenxing , many thanks for your support! Looking forward for weighted sampling .

**Comment by adamgayoso** [comment]
This is currently on the master branch and we will be releasing in the next few days.
