### ISSUE TITLE
Add library size prior as parameter of the module?

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#898]
>        local_l_mean = tensors[_CONSTANTS.LOCAL_L_MEAN_KEY]
>        local_l_var = tensors[_CONSTANTS.LOCAL_L_VAR_KEY]

Looking back at this, I am bugged that we need those two lines in the loss function everywhere. Also, these are not "local" parameters in scVI. It would be nicer to remove those and get them as global parameters in all of our models.

What do you think?

**Comment by adamgayoso** [comment]
Yeah it's on the list, just haven't gotten to it.
