### ISSUE TITLE
Readme refactor

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#899]
Ideas. Feel free to modify as you see fit

- [ ] Remove scvi transitioning to scvi-tools
- [ ] Add http links to Pytorch, pytorch lightning, scanpy and pyro
- [ ] add the new models implemented like stereoscope, cell assign and peakvi
- [ ] refer to the skeleton we are building
- [ ] add the newest tutorials like stereoscope and the scanvi cell annotation from seed labeling

**Comment by adamgayoso** [comment]
I like all these points, we should also make clear that

- scvi-tools is a framework to build single-cell focused probabilistic models, and features implementations of the following models...
