### ISSUE TITLE
make progress bar optional

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scvi-tools#904]
It would be great to have global package option or a custom train method option for disabling the progress bar.
it takes up a lot of space on a log file (e.g., below) 

Epoch 711/2000:  36%|███▌      | 710/2000 [01:09<02:11,  9.81it/s, loss=4.8e+06, v_num=1]
Epoch 711/2000:  36%|███▌      | 711/2000 [01:09<02:11,  9.81it/s, loss=4.8e+06, v_num=1]
Epoch 711/2000:  36%|███▌      | 711/2000 [01:09<02:11,  9.81it/s, loss=4.8e+06, v_num=1]
Epoch 712/2000:  36%|███▌      | 711/2000 [01:09<02:11,  9.81it/s, loss=4.8e+06, v_num=1]
Epoch 712/2000:  36%|███▌      | 712/2000 [01:09<02:13,  9.68it/s, loss=4.8e+06, v_num=1]
Epoch 712/2000:  36%|███▌      | 712/2000 [01:09<02:13,  9.68it/s, loss=4.79e+06, v_num=1]

These lines in the trainer could be called only if a flag is set to true:

bar = ProgressBar()
        kwargs["callbacks"] += [bar]

**Comment by romain-lopez** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/1686

<3 pytorch lightning, I can close this issue

**Comment by romain-lopez** [comment]
So actually that parameter doesn't work since we have a custom progress bar and callback. So we need to do:
+ add a flag on our generic trainer "disable_progress_bar" that disable the custom callback. That will activate the vanilla pytorch lightning progress bar
+ send progress_bar_refresh_rate=0 to the parent trainer, to disable the parent progress bar

**Comment by adamgayoso** [comment]
I'm not sure that will work because our progress bar is custom
