### ISSUE TITLE
LossRecorder fixes

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scvi-tools#993]
1. The kwargs aren't mentioned in the documentation, some examples might help too.
2. It also seems reasonable to set the kl local default to `torch.Tensor([0])`, maybe even reconstruction_loss too
3. On a related note, the loss isn't being logged in our training plan `self.log(loss, on_epoch=True)` should be added to train steps. This is related to the second point and enables a default value of 0 for reconstruction loss. Clearly this would throw off all elbo logging, and perhaps there's even a way around that, e.g., a `record_elbo` flag in `LossRecorder` init that is detected in our training plans and skips over tabulation of ELBO in this case.

**Comment by mjayasur** [comment]
How do I get access to the loss recorder from training_epoch_end?

**Comment by mjayasur** [comment]
When should the `record_elbo` be True?
