### ISSUE TITLE
Cell-Cycle Scoring and Regression

### ISSUE THREAD

**Issue by wangjiawen2013** [YosefLab/scvi-tools#998]
Hi,
Scanpy  and seurat can regress cell cycle effect (https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb)
Could these covariates (such as cell cycle score, total UMI counts) be registered using the continuous_covariate_keys argument ? Do I need to correct for cell cycle score and total UMI counts using scvi-tools ? Just like https://docs.scvi-tools.org/en/stable/user_guide/notebooks/api_overview.html

**Comment by adamgayoso** [comment]
No need to explicitly handle library size (total UMI counts) as it's baked into scVI. 

You can choose to use the cell cycle score as a covariate, but you may also extract the cell cycle genes out of `adata.X` and put them (in log normalized form) in `adata.obs` and use those as continuous covariates.

**Comment by adamgayoso** [comment]
I'm going to close this, if you have any other questions of this nature, please use our forum:

https://discourse.scvi-tools.org/
